### ISSUE TITLE
ORACLE - Add support of CLOB data type

### ISSUE THREAD

**Issue by BigOHenry** [dg/dibi#347]
- `CLOB` is replacement for `LONG` (which is deprecated). Its used for long strings. 
- Dibi will return on fetch `OCI-Lob` class:
![image](https://user-images.githubusercontent.com/15823552/70140882-069bca00-1696-11ea-8312-77e07eec9acb.png)

`OCI-Lob`: https://www.php.net/manual/en/class.OCI-Lob.php

**Comment by dg** [comment]
Can you send PR?

**Comment by milo** [comment]
Dibi already returns `OCI-Lob` objects.

**Comment by BigOHenry** [comment]
Yeah i wrote that at first post. But i thought it should return string.

**Comment by BigOHenry** [comment]
> Can you send PR?

I will. But first i will make more testing of implementing it. There is a OCI8 driver problem with `OCI-Lob` class. At PHP exists `OCI_Lob` class:
https://bugs.php.net/bug.php?id=58319
https://bugs.php.net/bug.php?id=45853

**Comment by milo** [comment]
> Yeah i wrote that at first post. But i thought it should return string.

I don't think so that automatic CLOB to string conversion is a good way. Let's say that 100 rows can grow from few kilobytes to gigabytes. `OCI-Lob` provides more methods than string conversion. For example `OCI-Lob::export()` which saves contents to file.

Automatic CLOB to string conversion could work with explicit type set, like:
```php
$db->query(...)->setType('clobField', Dibi::TEXT)
```

**Comment by BigOHenry** [comment]
I thought more about it and you are right. Closing issue.
